#This file will build image based on ubuntu 20.04 and required packages to deploy a Laravel APP.
FROM ubuntu:20.04
############################
#####  CONFIG ZONE #########
ENV APP_DB=gluedb
ENV APP_DB_USER=root
ENV APP_DB_PASS=root123
ENV WEB_SERVER=
############ END ###########
# 'Conf' Folder contains customise able configuration file such as .env, Database, and Virtualhost file of NGINX
WORKDIR /var/www/
COPY Entrypoint/* /mnt/glue/
ENV TZ=Asia/Dhaka \
    DEBIAN_FRONTEND=noninteractive
# Here we are going to install required packages for our Laravel Project
RUN apt update -y; \
    apt install lsb-release ca-certificates apt-transport-https software-properties-common curl  unzip mysql-server git nginx -y --no-install-recommends; \
    add-apt-repository ppa:ondrej/php -y; \ 
    apt install php8.1 php8.1-bcmath php8.1-xml php8.1-fpm php8.1-mysql php8.1-zip php8.1-intl php8.1-ldap php8.1-gd php8.1-cli php8.1-bz2 php8.1-curl php8.1-mbstring php8.1-pgsql php8.1-opcache php8.1-soap php8.1-cgi -y --no-install-recommends; \
    apt remove apache2 -y; \
    sed -i 's/;extension=gd/extension=gd/g' /etc/php/8.1/cli/php.ini; \
    # Composer Installation Starting Here
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer; \
    # DB Initialing 
    service mysql start; \
    mysql -uroot -e "CREATE DATABASE $APP_DB;"; \
    mysql -uroot -e "CREATE USER $APP_DB_USER@'localhost' IDENTIFIED BY '$APP_DB_PASS';"; \
    mysql -uroot -e "GRANT ALL ON $APP_DB.* TO $APP_DB_USER@'localhost';"; \
    cd /mnt/glue/; \
    # Creating Directory for Glue App
    mkdir /var/www/html/glue; \
    cd /var/www/html/glue; \
    # Git Init and Pulling Repo.
    #git init; \
    #git remote add origin  https://github.com/Team-Cloudboost/laravel-app.git; \
    #git pull origin main; \
    cp /mnt/glue /var/www/html/glue \
    sed -i "s/DB_DATABASE=/DB_DATABASE=$APP_DB/g" /var/www/html/glue/.env; \
    sed -i "s/DB_USERNAME=/DB_USERNAME=$APP_DB_USER/g" /var/www/html/glue/.env; \
    sed -i "s/DB_PASSWORD=/DB_PASSWORD=$APP_DB_PASS/g" /var/www/html/glue/.env; \
    # Configuring the APP
    cd /var/www/html/glue; \
    composer install; \
    php artisan key:generate; \
    # Configuring web Server
    cp /var/www/html/glue/config/glue.conf /etc/nginx/sites-available/glue.conf; \
    ln -s /etc/nginx/sites-available/glue.conf /etc/nginx/sites-enabled/glue.conf; \
    rm -rf /etc/nginx/sites-enabled/default; \
    sed -i "s/IP_ADDRESS_OR_DOMAIN/$WEB_SERVER/g" /etc/nginx/sites-enabled/glue.conf; \
    # Import Project Database 
    mysql -uroot $APP_DB < /var/www/html/glue/database.sql;
    
RUN ["chown", "-R", "www-data:www-data", "/var/www/html/glue/storage"]
RUN ["chown", "-R", "www-data:www-data", "/var/www/html/glue/bootstrap/cache"]
# Export Port 80 to access the web app
EXPOSE 80:80
RUN ["chmod", "+x", "/cloudboost/start.sh"]
ENTRYPOINT ["sh", "/cloudboost/start.sh"]
